package com.arkhamcards.v2.ui.utils.text.model

import com.arkhamcards.v2.ui.icons.AppIcon

object IconRegistry {
    private val icons = hashMapOf(
        "guardian" to AppIcon.Guardian,
        "seeker" to AppIcon.Seeker,
        "mystic" to AppIcon.Mystic,
        "rogue" to AppIcon.Rogue,
        "survivor" to AppIcon.Survivor,
        "neutral" to AppIcon.Neutral,
        "willpower" to AppIcon.Willpower,
        "intellect" to AppIcon.Intellect,
        "combat" to AppIcon.Combat,
        "agility" to AppIcon.Agility,
        "wild" to AppIcon.Wild,
        "elder_sign" to AppIcon.ElderSign,
        "skull" to AppIcon.Skull,
        "cultist" to AppIcon.Cultist,
        "tablet" to AppIcon.Tablet,
        "elder_thing" to AppIcon.ElderThing,
        "auto_fail" to AppIcon.AutoFail,
        "per_investigator" to AppIcon.PerInvestigator,
        "weakness" to AppIcon.Weakness,
        "action" to AppIcon.Action,
        "reaction" to AppIcon.Reaction,
        "free" to AppIcon.Free,
        "fast" to AppIcon.Free,
        "bullet" to AppIcon.Bullet,
        "guide_bullet" to AppIcon.GuideBullet,
        "curse" to AppIcon.Curse,
        "bless" to AppIcon.Bless,
        "frost" to AppIcon.Frost,
        "seal_a" to AppIcon.SealA,
        "seal_b" to AppIcon.SealB,
        "seal_c" to AppIcon.SealC,
        "seal_d" to AppIcon.SealD,
        "seal_e" to AppIcon.SealE,
        "day" to AppIcon.Day,
        "night" to AppIcon.Night,
        "codex" to AppIcon.Codex,
        "tdc_rune_a" to AppIcon.TdcRuneA,
        "tdc_rune_b" to AppIcon.TdcRuneB,
        "tdc_rune_c" to AppIcon.TdcRuneC,
        "tdc_rune_d" to AppIcon.TdcRuneD,
        "tdc_rune_e" to AppIcon.TdcRuneE,
        "tdc_rune_f" to AppIcon.TdcRuneF,
        "tdc_rune_g" to AppIcon.TdcRuneG,
        "tdc_rune_h" to AppIcon.TdcRuneH,
        "tdc_rune_i" to AppIcon.TdcRuneI,
        "tdc_rune_j" to AppIcon.TdcRuneJ,
        "tdc_rune_k" to AppIcon.TdcRuneK,
        "tdc_rune_l" to AppIcon.TdcRuneL,
        "tdc_rune_m" to AppIcon.TdcRuneM,
        "tdc_rune_n" to AppIcon.TdcRuneN,
        "tdc_rune_o" to AppIcon.TdcRuneO,
        "tdc_rune_p" to AppIcon.TdcRuneP,
        "tdc_rune_q" to AppIcon.TdcRuneQ,
        "tdc_rune_r" to AppIcon.TdcRuneR,
        "tdc_rune_s" to AppIcon.TdcRuneS,
        "tdc_rune_t" to AppIcon.TdcRuneT,
        "tdc_rune_u" to AppIcon.TdcRuneU,
        "tdc_rune_v" to AppIcon.TdcRuneV,
        "tdc_rune_w" to AppIcon.TdcRuneW,
        "tdc_rune_x" to AppIcon.TdcRuneX,
        "tdc_rune_y" to AppIcon.TdcRuneY,
        "tdc_rune_z" to AppIcon.TdcRuneZ,
        "moon" to AppIcon.Moon,
    )

    fun glyph(name: String): String? = icons[name]?.glyph
}